version: '3.5'
services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
    - MONGO_DATA_DIR=/data/db
    - MONGO_LOG_DIR=/dev/null
    volumes:
    - ./docker/data/db:/data/db
    ports:
        - 27017:27017
    command: mongod 

  nodejs:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nodejs
    restart: always
    environment:
      WAIT_HOSTS: mongo:27017
    ports:
      - "3000:3000"
    volumes:
          - .:/app/
          - /app/node_modules
    links:
          - mongo
    depends_on:
          - mongo     
    command: npm start

    